### ISSUE TITLE
Time Conversion into wrong Time Zone!

### ISSUE THREAD

**Issue by Matdog97** [fl0-at/iCalStripper#3]
Hello Flo_at!

I've downloaded the ical-stripper to strip an event plan. The event plan was entered in the Time Zone GMT+2, but every Time i strip the ical it changes the time in the calender entrys to GMT+0 or GMT +1, so it doesnt line up with the correct entry.
![Billd](https://github.com/fl0-at/iCalStripper/assets/143907174/393f36ff-527b-4f7a-b259-d04c6b09764a)

Below: Correct calender entry
Above: New (stripped) calender entry

**Comment by fl0-at** [comment]
Fixed with v0.9.0
